### ISSUE TITLE
Misplace of the shebang line (#!/bin/bash) in clang-ocl script

### ISSUE THREAD

**Issue by iq136boy** [RadeonOpenCompute/clang-ocl#45]
Got an error related to the clang-ocl in MIOpen, which is caused by the misplace of the shebang line in the script. The shebang line should be placed at the very beginning in the script (before the copyright statement). Try to fix that, but seems that I do not have access to this repo.

**Comment by bcahoon** [comment]
Thanks for reporting the issue! I created a PR https://github.com/RadeonOpenCompute/clang-ocl/pull/46

**Comment by iq136boy** [comment]
> Thanks for reporting the issue! I created a PR #46

Thanks for addressing this. Since the PR is merged, I will close this issue.

**Comment by iq136boy** [comment]
Issue resolved.
